name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release /p:UseSharedCompilation=false

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Publish
      run: dotnet publish --no-restore --no-build --configuration Release -o ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-build
        path: ./publish/
        if-no-files-found: warn
